version: '2'

services:

  # backend application
  backend:
    image: timetrack/backend:1.0.0
    ports:
      - 8080:8080
    links:
      - mongo
      - elasticsearch
    volumes:
      - ./backend/target/log:/var/log
  mongo:
    image: timetrack/mongo:1.0.0
    ports:
      - 27017:27017
    volumes:
      - timetrack-mongo-data:/data/db
  redis:
    image: timetrack/redis:1.0.0
    ports:
      - 6379:6379
    volumes:
      - timetrack-redis-data:/var/lib/redis

  # frontend
  frontend:
    image: timetrack/frontend:1.0.0
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./frontend:/html

  # infra
  elasticsearch:
    image: timetrack/elasticsearch:1.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - timetrack-elastic-data:/usr/share/elasticsearch/data
  kibana:
    image: timetrack/kibana:1.0.0
    volumes:
     - ./docker/containers/kibana/config/:/opt/kibana/config/
    ports:
     - 5601:5601

volumes:
  timetrack-redis-data: {}
  timetrack-mongo-data: {}
  timetrack-elastic-data: {}