version: '2'

services:

  # backend application
  backend:
#    image: timetrack/backend:latest
    build: ./backend
    hostname: timetrack-backend
    ports:
      - 8080:8080
    links:
      - mongo
      - elasticsearch
  mongo:
#    image: timetrack/mongo:latest
    build: ./docker/containers/mongo
    hostname: timetrack-mongo
    ports:
      - 27017:27017
    volumes:
      - timetrack-mongo-data:/data/db
  redis:
#    image: timetrack/redis:latest
    build: ./docker/containers/redis
    hostname: timetrack-redis
    ports:
      - 6379:6379
    volumes:
      - timetrack-redis-data:/var/lib/redis

  # frontend
  frontend:
    image: timetrack/frontend:latest
    hostname: timetrack-frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  # logging / stats
  elasticsearch:
#    image: timetrack/elasticsearch:latest
    build: ./docker/containers/elasticsearch
    hostname: timetrack-elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - timetrack-elastic-data:/usr/share/elasticsearch/data
  kibana:
#    image: timetrack/kibana:latest
    build: ./docker/containers/kibana
    hostname: timetrack-kibana
    volumes:
      - ./docker/containers/kibana/config/:/opt/kibana/config/
    ports:
     - 5601:5601

  # monitoring / metrics
  admin-ui:
    build: ./backend/admin-ui
    hostname: timetrack-admin-ui
    ports:
      - 8081:8081
  influxdb:
    build: ./docker/containers/influxdb
    hostname: timetrack-influxdb
    ports:
      - 2003:2003
      - 8086:8086
      - 8083:8083
      - 8090:8090
      - 8099:8099
    environment:
      - INFLUXDB_ADMIN_ENABLED: true
    volumes:
      - timetrack-influx-data:/var/lib/influxdb
    environment:
      INFLUXDB_DATA_ENGINE: tsm1

  prometheus:
    build: ./docker/containers/prometheus
    hostname: timetrack-prometheus
    volumes:
      - timetrack-prometheus_data:/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor
    depends_on:
      - cadvisor

  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 9091
    ports:
      - 8080:9091

  telegraf:
    build: ./docker/containers/telegraf
    hostname: timetrack-telegraf
    ports:
      - 8125:8125
    depends_on:
      - influxdb
      - grafana
    links:
      - backend
      - influxdb
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    build: ./docker/containers/grafana
    hostname: timetrack-grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - timetrack-grafana-data:/var/lib/grafana

volumes:
  timetrack-redis-data: {}
  timetrack-mongo-data: {}
  timetrack-elastic-data: {}
  timetrack-influx-data: {}
  timetrack-grafana-data: {}
  timetrack-prometheus_data: {}