version: '2'

services:

  # backend application
  backend:
    build: ./docker/backend
    ports:
      - 8080:8080
      - 9000:9000
      - 9300:9300
    networks:
      - application
    links:
      - mongo
      - elasticsearch
    volumes:
      - ./backend/target:/opt/backend
      - ./target/log:/var/log
  mongo:
    build: docker/mongo
    ports:
      - 27017:27017
    networks:
      - application
    volumes:
      - mongo-data:/data/db

  # frontend
#  frontend:
#    build: ./docker/frontend
#    ports:
#      - 3000:3000
#      - 3001:3001
#    volumes:
#      - ./frontend:/html
#    networks:
#      - application

  # infra
  elasticsearch:
      build: ./elasticsearch/
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      networks:
        - docker_elk
      volumes:
        - elastic-data:/usr/share/elasticsearch/data

  kibana:
    build: docker/kibana/
    volumes:
     - ./kibana/config/:/opt/kibana/config/
    ports:
     - 5601:5601
    networks:
     - docker_elk

networks:
  application:
    driver: bridge
  docker_elk:
    driver: bridge

volumes:
  mongo-data: {}
  elastic-data: {}